### ISSUE TITLE
能交流下实现思路嘛。

### ISSUE THREAD

**Issue by 9191app** [MuYanQin/hanziAnimation#4]
hanzi-writer的js库，到如何自己封装的framework

**Comment by MuYanQin** [comment]
封装后，打成framework不就行了吗

**Comment by 9191app** [comment]
大佬，没有word json数据也能写，这里的数据时从哪读取的呢，另外加上json的data如何调用呢

**Comment by 9191app** [comment]
你导出的framework 只支持模拟器 @MuYanQin

**Comment by 9191app** [comment]
有时间麻烦帮忙看看这里，当我使用本地json时，总是“WKJavaScriptExceptionMessage=ReferenceError:Can't find variable: require”

var ren = require('hanzi-writer-data/人');
var writer = HanziWriter.create('target', '人', {
  charDataLoader: function() {
    return ren;
  }
});
在使用本地json这块你是怎么处理的 ？多谢
