### ISSUE TITLE
大佬你好🧎‍♂️，能把源码发布出来吗？这个请求似乎有点过分🐶

### ISSUE THREAD

**Issue by lee18Cat** [MuYanQin/hanziAnimation#5]
hanziwriter这个库新版本更新了几个方法，暂停/继续，我正好需要这些功能，我的js很烂，想看看你是咋写的🙏

**Comment by MuYanQin** [comment]
我很久之前写的时候没有暂停的方法。我没写啊


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Lee <notifications@github.com&gt;
发送时间: 2020年5月13日 15:51
收件人: MuYanQin/hanziAnimation <hanziAnimation@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[MuYanQin/hanziAnimation] 大佬你好硫‍♂️，能把源码发布出来吗？这个请求似乎有点过分 (#5)





 
hanziwriter这个库新版本更新了几个方法，暂停/继续，我正好需要这些功能，我的js很烂，想看看你是咋写的🙏

**Comment by MuYanQin** [comment]
明天上班了，我发一下js。没有什么源码，就是封装人家js的，我也是菜鸟
发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Lee <notifications@github.com&gt;
发送时间: 2020年5月13日 15:51
收件人: MuYanQin/hanziAnimation <hanziAnimation@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[MuYanQin/hanziAnimation] 大佬你好硫‍♂️，能把源码发布出来吗？这个请求似乎有点过分 (#5)





 
hanziwriter这个库新版本更新了几个方法，暂停/继续，我正好需要这些功能，我的js很烂，想看看你是咋写的🙏

**Comment by lee18Cat** [comment]
哇，大佬回我了，谢谢啦

**Comment by lee18Cat** [comment]
> 明天上班了，我发一下js。没有什么源码，就是封装人家js的，我也是菜鸟 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Lee <notifications@github.com&gt; 发送时间: 2020年5月13日 15:51 收件人: MuYanQin/hanziAnimation <hanziAnimation@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[MuYanQin/hanziAnimation] 大佬你好硫‍♂️，能把源码发布出来吗？这个请求似乎有点过分 (#5) hanziwriter这个库新版本更新了几个方法，暂停/继续，我正好需要这些功能，我的js很烂，想看看你是咋写的🙏 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬

**Comment by MuYanQin** [comment]
不好意思 工作忙忘记了。把你邮箱给我 我先给你吧。有时间我再传上来

**Comment by lee18Cat** [comment]
547900997@qq.com------------------ 原始邮件 ------------------
发件人: "MuYanQin"<notifications@github.com>
发送时间: 2020年5月14日(星期四) 上午10:38
收件人: "MuYanQin/hanziAnimation"<hanziAnimation@noreply.github.com>;
抄送: "Lee"<547900997@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [MuYanQin/hanziAnimation] 大佬你好&#x1F9CE;&#x200D;♂&#xFE0F;，能把源码发布出来吗？这个请求似乎有点过分&#x1F436; (#5)




 
不好意思 工作忙忘记了。把你邮箱给我 我先给你吧。有时间我再传上来
 
&mdash;

**Comment by lee18Cat** [comment]
能请大佬喝杯咖啡吗☕️------------------ 原始邮件 ------------------
发件人: "MuYanQin"<notifications@github.com>
发送时间: 2020年5月14日(星期四) 上午10:38
收件人: "MuYanQin/hanziAnimation"<hanziAnimation@noreply.github.com>;
抄送: "Lee"<547900997@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [MuYanQin/hanziAnimation] 大佬你好&#x1F9CE;&#x200D;♂&#xFE0F;，能把源码发布出来吗？这个请求似乎有点过分&#x1F436; (#5)




 
不好意思 工作忙忘记了。把你邮箱给我 我先给你吧。有时间我再传上来
 
&mdash;

**Comment by MuYanQin** [comment]
已发 。很久之前写的了。希望对你有帮助

**Comment by lee18Cat** [comment]
thank you very much！！

**Comment by hanfengs** [comment]
想请教一下大佬，如何封装 JS 库，iOS 如何调用？

**Comment by hanfengs** [comment]
请教一下大佬，如何封装 JS 库，iOS 如何调用？源码能发我一份吗，yifan1223@gmail.com 谢谢大佬
